#!/bin/bash

DEPLOY_DIR=deployDir
DEPLOYED_JAR=$DEPLOY_DIR/AllMyCoins.jar
START_SCRIPT=AllMyCoins
DEPLOYED_START_SCRIPT=$DEPLOY_DIR/$START_SCRIPT

# Setup
mkdir deployDir

#Cleaning
rm $DEPLOYED_JAR
rm $DEPLOYED_START_SCRIPT

# Clean install
mvn clean install

# Deploy
cp target/AllMyCoins*.jar $DEPLOYED_JAR
cp $START_SCRIPT $DEPLOYED_START_SCRIPT