#!/bin/bash

DEPLOY_DIR=deployDir
DEPLOYED_JAR=$DEPLOY_DIR/allmycoins.jar
START_SCRIPT=allMyCoins
DEPLOYED_START_SCRIPT=$DEPLOY_DIR/$START_SCRIPT

# Setup
mkdir $DEPLOY_DIR

#Cleaning
rm $DEPLOYED_JAR
rm $DEPLOYED_START_SCRIPT

# Clean install
mvn clean package

# Deploy
cp target/*-jar-with-dependencies.jar $DEPLOYED_JAR
cp $START_SCRIPT $DEPLOYED_START_SCRIPT
chmod a+x $DEPLOYED_START_SCRIPT
