name: Java CI with Maven

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
      
          - name: Deploy script
        run: ./deploy

      - uses: actions/upload-artifact@v2
        with:
          name: allMyCoins
          path: releaseDir/allMyCoins.zip